name: CatFTtrapSkins
version: 2.0-SNAPSHOT
main: me.inotwhitecat.catfttrapskins.CatFTtrapSkins
api-version: 1.16
author:
  - CatsDev
commands:
  CatFTtraps:
    description: "Команда для работы с ловушками и пластами."
    usage: "/<command> give <plast/trap> <trapName> <кол-во>"
